### PR TITLE
Surprise Orbpdate

### PR DESCRIPTION
**Pull request by Jacquerel**
**The Bad News**
There was a tram update in this set of changes. It added a new required structure to trams.
image
The Biodome tram boat is in a uh... slightly sorry state 😔 
All the machines are overlaid on one tile, and the two non-table tiles are underwater...
@Profakos may need to perform some mapping in order to resolve this

Featuring other features:
- Vent Pumps can be overclocked, allowing them to ignore pressure until they damage themselves.
- You can now breathe N2O to get high.
- Robotic parts can once again make you spaceproof.
- Blade Heretics can now sculpt their knives from Titanium instead of Silver (or keep using Silver).
- Added a larger afro.
- Traitors added after the round starts no longer have access to secondary objectives.
- The Wizard's Den has been remapped.
- The Free Golem Ship has also been rempped.
- Hallucinators may see a terrifying vision of their mother.
- Revenants can communicate with the living with ouija boards.
- The Aurora Caelis event now modifies the colour of space appropriately.
- The tram has been upgraded.
-- You can now emag tram spoilers to cause it to do extra damage.
-- The tram can be manually driven using its control panel.
-- Engineers can perform tram maintenance and end the tram malfunction event early.
-- The tram can be repaired and rebuilt if destroyed.
-- You can now redecorate the tram more easily as a player.

### CODE REVIEW

**Comment by Profakos** [comment]
Maybe I have to do unique chairs that add TRAIT_IMMERSE_STOPPED in the /datum/element/give_turf_traits element. Not sure if it would work with the tram platform itself, but i will look closer.

**Comment by Profakos** [comment]
Oh, we could put a catwalk on the tram maybe, under the chairs? Those also prevent sinking. Hopefully compatible with the platforms.

**Comment by Profakos** [comment]
Made the PR with the fix.

**Comment by Jacquerel** [comment]
I think this might be an upstream issue where it wants to use the same icon state for two things but generates it in two different ways...

**Comment by Profakos** [comment]
I am so confused...

**Review by lizardqueenlexi — APPROVED** [review]

**Pull request merged**
