### PR TITLE
New CentCom emergency wing.

### PR DESCRIPTION
**Pull request by lizardqueenlexi**
## About The Pull Request

This PR uses an automapper template to replace the CentCom emergency wing with a brand-new one, based on a now-removed map template from Skyrat. This new wing significantly augments the emergency area with a large variety of amenities:

- A customs checkpoint outside of the shuttle dock, which can be locked down if manned.
- A prisoner processing center, where captured antags can be taken from the emergency shuttle to a secure holding cell to really think about what they've done.
- A trauma bay, complete with IVs and a blood freezer, two stasis beds, a surgery setup, a cryotube, and a variety of medical supplies.
- A bar, where crew can get drunk after the latest shift went horribly wrong. Can be optionally staffed by an admin-spawned character, or by anyone who decides to hop the bar.
- A cafeteria, featuring a variety of randomly-spawned meals for hungry crew members.
- A central memorial garden, where the Tomb of the Unknown Employee rests.
- A restroom, complete with showers, just in case.
- An "emergency dorms" area, with four separate rooms, a common area, a small gym, and a laundry room. Perfect for decompressing after a long day.
- Various vending machines and benches.

This template leaves most admin-only areas of CentCom untouched, with one exception - it completely destroys the Grand Courtroom to make space for the dorms. It also mostly ruins the admin prison. This should be fine, since these rooms have literally never been used on Orbstation for anything.

A few miscellaneous features have been added to support this map, and may find use elsewhere as well:

- CentCom departmental doors, with colored stripes for security, medical, and common/service areas.
- A random spawner for Ready-Donk meals, used in the dorm freezers.
- A six-part decal of Nanotrasen's logo, plastered prominently in front of the cafeteria.

## Why It's Good For The Game

Many players have expressed a desire for a space to decompress and unwind in after the round is over. The current CentCom emergency wing is terrible for this - it's simply a large, empty room, designed not for RP but for the assumption that everyone will be running around randomly murdering each other the moment the shuttle arrives. As random deathmatches at CentCom are already against Orbstation's rules, this provides a hopefully-appealing alternative to awkwardly standing around in an empty space waiting for the round to reset.

Some of the space provided is functional, and some is just for RP flavor. Most prominent is the Trauma Bay, located immediately outside of the shuttle. This miniature medbay gives doctors a space to finish working on patients they couldn't revive on the way home, and also provides a space for people to limp to if a traitor decided to shoot them several times just before the shuttle arrived. The Prisoner Processing area also gives a place to actually send captured antags at the end of the round, rather than awkwardly shuffling them around outside of the shuttle brig.

The rest of the space provided is purely for decompression and finishing up RP - whether that's drinking in the bar, getting a dorm room for some quiet time, having a meal, or just sitting on one of, like, 30 benches. In light of having actual RP space available, I would propose increasing the round-end timer length somewhat, perhaps as long as 5 minutes. That way, those who want to finish things up have time to do so, and those who don't can simply park their character somewhere and tab out for a few minutes.

(It would be helpful to also have a displayed timer somewhere before the world resets, but this is not included in this PR).

## Changelog

:cl:
add: Added a new, extensive emergency wing to Central Command.
add: Added a food spawner, a floor decal, and some special doors for flavor.
del: Removed the CentCom courtroom.
/:cl:

### CODE REVIEW

**Review by flowercuco — APPROVED** [review]
i like the monastery shuttle more than the meteor but thats not enough to block this. did you test the lance shuttle? thats the only one that could be worrisome i can think about due to its shape

**Comment by lizardqueenlexi** [comment]
it doesn't work on the lance shuttle. fuck.

**Comment by flowercuco** [comment]
sorry!!!!!!!!!!!!!!!!!!!!!

**Comment by lizardqueenlexi** [comment]
I've shifted the entire emergency wing west by eight tiles, so that the docking side is aligned with the original CentCom. This makes wide shuttles work properly again.

**Pull request merged**
