### PR TITLE
Orb Stasis update 2023 06 24

### PR DESCRIPTION
**Pull request by Profakos**
Issues:

- ~~Coloured snouts are not working properly, they just apply the original snout a second time, seems like it? Coloured stripes work properly. I need help looking into this, so I am drafting this for now.~~ Fixed!
- Due to hair traits having been moved to heads instead of species, I couldn't make infectious zombies keep your hair... I don't consider this blocking though, but I don't know how to fix this. 

Updates from upstream:

- Tweaks and improvements for the fugitive hunters
- Things being covered in acid now emit green bubbles
- Shipping manifests labelled as erroneous due to missing contents are now guaranteed to be missing contents
- Shipping manifests now display repeated items on a single line
- Latejoining crew start with emergency large crowbars if arrivals is not powered (so on Orb you get two now...)
- Armour penetration calculation is now the inverse function of armour stacking.
- The Curator's barcode scanner has been simplified into 2 modes: check-in and add to inventory.
- The Book bag can now hold posters.
- The library console can now lend books out easier with a dropdown menu to all inventory books.
- New ghost and death chat notifications
- Shuttle events! Things might happen outside the shuttle as you travel
- Rotting food gets stinklines
- Adds the "Access Request" form. (@lizardqueenlexi  this requires a config update, blank.json )
- Several nullrods have been resprited
- Chef equipment vendor has been given categories
- The Vorpal Scythe, a special null rod variant that gains power from beheading people! But it is fickle about when and how you use its power. Replaces the Reaper Scythe.
- air sensor's are craftable
- Refactors a bunch of species traits into flags for the head bodypart
- Limbgrower resprited
- Adds digital wall clocks!
- And many, many fixes and sprite tweaks!
- Wizarditis now forces you to cast a specific spell every now and then
- Xenos have been rebalanced! 
- You can craft plastitanium shards

Biodome:
- Science is now more of a wasteland!

### CODE REVIEW

**Comment by Profakos** [comment]
image
cat toy is broken

**Comment by Profakos** [comment]
Cat toy has a worn icon state now, it only had a worn icon. 
Updates ashwalker screenshot test too.

**Comment by Profakos** [comment]
>  [22:49:15] Runtime in stack_trace.dm,4: /datum/progressbar created with invalid user (code/datums/progressbar.dm:28)
  proc name:  stack trace (/proc/_stack_trace)
  usr: *no key*/(Garden Gnome)
  src: null
  call stack:
   stack trace("/datum/progressbar created wit...", "code/datums/progressbar.dm", 28)
  /datum/progressbar (/datum/progressbar): New(Garden Gnome (/mob/living/basic/garden_gnome), 10, Garden Gnome (/mob/living/basic/garden_gnome))
  do after(Garden Gnome (/mob/living/basic/garden_gnome), 10, Garden Gnome (/mob/living/basic/garden_gnome), 0, 1, null, Garden Gnome (/mob/living/basic/garden_gnome), 1)
  /datum/component/ground_sinkin... (/datum/component/ground_sinking): sink once(Garden Gnome (/mob/living/basic/garden_gnome))
  /datum/component/ground_sinkin... (/datum/component/ground_sinking): start sinking(Garden Gnome (/mob/living/basic/garden_gnome))

Odd biodome issue

**Comment by Profakos** [comment]
image
grrr

**Comment by Profakos** [comment]
> CentCom Security at CentCom Recovery Wing (180,88,1) failed to find a valid airlock to cyclelink with!
CentCom Security at CentCom Recovery Wing (180,88,1) failed to find a valid airlock to cyclelink with!
CentCom Security at CentCom Central Control (176,86,1) failed to find a valid airlock to cyclelink with!
CentCom Security at CentCom Central Control (176,86,1) failed to find a valid airlock to cyclelink with!

Non blocking error in maploading

**Review by lizardqueenlexi — APPROVED** [review]

**Pull request merged**
