### PR TITLE
New Positive Quirk: Throwing Arm

### PR DESCRIPTION
**Pull request by flowercuco**
## About The Pull Request

This quirk massively buffs Garth Plagueman and anyone else who wishes to enter the realm of throwing deadly origami paper planes, as if you have this quirk thrown items will fly faster and go further than they did before! This is the first of FOUR quirks that I hope to add to orbstation before PRing upstream, me and Jac could not find a way to do this without messing with the .carbon on tgcode so hopefully thats ok.

## Why It's Good For The Game

we need more positive quirks more than anyone else and this is clearly the most important one of the four i want to do

## Changelog

:cl:
add: new positive quirk that throws things further and faster
add: said quirk means you will bypass the 75% fail to throw trash away/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
I have to abstain from reviewing this because I've already read it so I won't have any new insights

**Review by skylord-a52 — APPROVED** [review]

**Comment by skylord-a52** [comment]
Resolve the conflict and this can be merged

**Comment by flowercuco** [comment]
when you merge this one ill fix the inevitable new conflict on the next one

**Comment by flowercuco** [comment]
why
image

**Pull request merged**
