### PR TITLE
Magazines!

### PR DESCRIPTION
**Pull request by skylord-a52**
## About The Pull Request

Adds a new book subtype, the magazine. These are mostly intended for rp and flavor, but reading them does give a small mood boost.

The PR as it stands is incomplete -- most or all of the following should be done by me or somebody else before it's merged:

- [x] Add a base sprite for the generic magazine -- this is why all the checks are currently failing.
- [x] Add sprites for the specific magazines
- [x] Maybe add a few more specific kinds of magazine. Mothboys Monthly was the one that inspired this PR, but the others are just the few I could think up on the spot.
- [x] Verify that magazines spawn in maintenance. I think they might already do this, because they're a subtype of book and books can, but they might not.
- [x] Add magazines to the pool of junk mail items.
- [ ] If we want, add newspaper stands that sell them and/or cargo orders that contain a bunch. This might have to be done upstream though.

Also, I'm not sure if this should be done here or sent upstream. We can decide that when the PR is in a more mergeable state.

## Why It's Good For The Game

Someone mentioned it on discord and I thought it would be a fun little feature to add -- something relatively easy to make but that would still add something to the game. To me, they feel like they fill a similar niche to posters.

## Changelog

:cl:
add: Magazines!
/:cl:

### CODE REVIEW

**Comment by SuperSayu** [comment]
I would definitely also add comics and/or manga in the same category, and potentially, allow rare spawn valuable (Original Volume 1!) versions that can be sold in cargo.  Top dollar for mint condition only, never-read, of course.

A magazine display rack structure would be nice, just a thing that displays the top magazine in its sprite and when you click on it also shows other available mags.

Also it would be boss if reading a magazine had a chance of making you emote reactions, eg, funny comics make you laugh, reading a scandalous article made you gasp dramatically, reading about ghosts or whatever makes you scream, etc.

**Comment by flowercuco** [comment]
i like magazines and have suddenly become magazine pillled and thus am thinking about how to turn magazines into CONTENT

1) new positive quirk where as long as you have one of the items in magazine.dm it gives you a mood buff & you have a special magazine collectors satchel that persistently stores a number of magazines. if you collect a number of of RARE MAGAZINES you get BOOSTED MOOD BUFF but watch out!

2) following from what sayu said RARE MAGAZINES should exist, be they misprints or special editions or whatever each CATEGORY OF MAGAZINE should have a RARE VARIANT.

3) following off of the like, way pizza crates technically work, cargo now has a selection of new orders that you can do, of different categories of magazine or a completely random selection of mags. now, the way that this is good for people who dont have the magazine hunter quirk is that similar to how pizza crates can sometimes spawn different pizzas and can even sometimes spawn an INFINITE BOX OF PIZZA!!!, when you order any magazine you have a chance of getting a RARE VARIENT, which you can somehow sell for more cash than you paid, OR you can get a BONUS GOODIE PRIZE! similar to how you could order in REAL X RAY SPECS in old comic ads and stuff. with the bonus goodie prize usually being a bust (obvs) but sometimes being.... real???? 

i hope none of this derails your magazines idea too much i just got a bit carried away

**Comment by skylord-a52** [comment]
> flower cuco said: stuff

these are good ideas, but theyre outside the scope of this pr. ...if i ever even get around to finishing it, that is.

**Comment by flowercuco** [comment]
something that might be more in scope is, off of your magazine stand idea, maybe "magazine stand kit" or something similar where you can just decide to somehow buy a bunch of mags and sell them on the station as Your Gimmick for the round? hmmm thats giving me other ideas though. ill leave it at that instead of continuing to be too magazine pilled.

**Comment by skylord-a52** [comment]
TODO: fix bug where reading two magazines in a row locks you out of further mood boosts for both, but only gives you the moodlet for one of them. 

(is this an issue with tgstation books as well??)

**Comment by skylord-a52** [comment]
Magazine racks, map edits, and cargo orders will have to wait because this "super easy" pr has been sitting on the backburner with school for too long and I can't be bothered. For now magazines will be mostly found by chance in maintenance and mail. Opening PR for review

**Review by lizardqueenlexi — APPROVED** [review]

**Pull request merged**
