### PR TITLE
Pre-game role heatmap

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

image

Adds a basic "heatmap" to what roles people have selected in the pre-game lobby.

How this works:
- A counter displays how many _unique players_ have selected at least one role in a department. You can pick 7 service jobs but still are only listed once for that department.
- A counter underneath that displays how many people have a _high priority_ job in a specific department, they are very likely to assume that job.
- A separate header lists High, Medium, and Low priority for each Head of Staff. This shows the highest selected priority among all players, but not how many players selected that priority. AI counts as a Head of Staff for purposes of this table.
- These only occur for players who have hit Ready. Until you hit Ready you are not represented.
- **Prisoner** and **Assistant** don't count against any department.
- Departmental assistants count against their department.

This is hopefully both detailed enough to be useful while not useful enough to give away weird information or form strange and undesirable cultural side-effects.

## Why It's Good For The Game

People really want it.
Makes people more confident about selecting head roles and perhaps not becoming the Captain.
May lead to less lopsided departments.

## Changelog

:cl:
qol: A little bit of information about what other people are going to play is visible before the round begins.
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
Tentatively undrafting
I still haven't managed to test this with more than one client, and there's still a visual bug where the boxes will sometimes change size until you change tab
I unfortunately just don't know how to fix these at the moment without just trying it on live

**Comment by Jacquerel** [comment]
Actually drafting again until we do like a formal test

**Comment by Jacquerel** [comment]
Updated with new UI changes. Potentially now ready for use.

**Comment by Jacquerel** [comment]
it stopped working for some reason 😔 
this branch is pretty behind though, probably won't be able to fix it up until later this month

**Comment by Jacquerel** [comment]
image

**Comment by Jacquerel** [comment]
I am confident that this is now ready for use (or at least one more test)

**Review by lizardqueenlexi — APPROVED** [review]

**Pull request merged**
