### PR TITLE
Department Assistants!

### PR DESCRIPTION
**Pull request by pizie11**
## About The Pull Request
Completes https://github.com/lizardqueenlexi/orbstation/issues/34

Creates 4 new occupations, meant to be "Assistants with a little extra access". They are counted as a part of that department.

### Service Assistant
**Name:** Waitron
**Description:** Bus tables, work for tips
**Open Positions:** 2
**Access:** Service
**Extra Access:** Bar, Hydroponics, Kitchen, Theatre

### Engineering Assistant
**Name:** Tech Support
**Description:** Make your own pet projects, get called away to fix every little thing.
**Open Positions:** 2
**Access:** Engineering, Maintenance (Guaranteed if disabled in config)
**Extra Access:** Construction, Engine Equipment, External Airlocks

### Medical Assistant
**Name:** Medical Assistant
**Description:** Handle patients coming in and out of medbay, lack a medical license.
**Open Positions:** 2
**Access:** Medical
**Extra Access:** Morgue, Surgery

### Science Assistant
**Name:** Lab Assistant
**Description:** Witness the marvels of modern age technology, and be a test subject for them.
**Open Positions:** 2
**Access:** Science
**Extra Access:** Research, Xenobiology

TODO:
- See if there isnt any way I can't tie this to security department choice instead of it's own occupation, or if that is even wanted for assistant-level jobs
- more unique jumpsuits?

(Slightly outdated screenshots, the brig clerk was axed because a lawyer already works as that kind of job)
showcase1
showcase2
(pretend servicer is replaced with waitron here plsthx)
image

## Why It's Good For The Game
Flavorful assistant occupations are fun, also being able to work a lower position in a department can add some variety while still giving you the low expectation of actually doing things for that department.

## Changelog
:cl: Pizzie
add: Added five new Assistant jobs! Waitron, Tech Support, Medical Assistant, Lab Assistant, and Brig Clerk
/:cl:

### CODE REVIEW

**Comment by flowercuco** [comment]
I would put all of them under assistants if you can't have it be a drop down like sec officers. i dont /love/ servicers but i also dont know what would be better. "busser" as in like a busboy i guess?

> Name: Brig Clerk
I think maybe Deputy might be better for this one but I'm unsure!

> Description: (To be Written)
"Make donuts while the rest of security is killed by alien invaders."

i dont know whats in the mineral storerooms but maybe not giving access to those or the aux base would be better? those both feel like things that you'd only want the assistant to mess with under supervision...

this is a bit outside the scope of what youre doing and more musing for me personally, i wonder how hward it would be to add something to all of the department head computers to auto promote an assistant to a real role....

**Comment by pizie11** [comment]
Hitting all the points in the prev comment:

I will put them all under the assistant category then, I agree with that.

I was thinking Waitron works best for service assistant, so I'm sticking with that.

I don't want to name a sec assistant deputy just because deputys in a normal game are taken from existing staff, I was thinking the role of a brig clerk could be literally just to be a clerk/intern for the brig, greeting people who go up to the doors and making sure there are always fresh donuts.

I do love this description, I'll use it

Yeah I'll just remove mineral and aux base for all the accesses, I hadnt considered what that gave in terms of tools.

Maybe! iirc all assistants are currently only changeable by the HoP, but I don't see why any head cant do it, since they answer to "absolutley everyone"

**Comment by Profakos** [comment]
> Maybe! iirc all assistants are currently only changeable by the HoP, but I don't see why any head cant do it, since they answer to "absolutley everyone"

Do you mean, allow Heads Of Staff to paint the relevant assistant trims with their ID/PDA printer and ID console?

**Comment by Jacquerel** [comment]
If there is a way to make this a drop-down pref like security guards that would be nice, but there's advantages to this system to.  
Doing it like guards would mean no way to put limits on them, or different priorities if you wanted to do that for some reason.

**Review by Jacquerel — APPROVED** [review]

**Comment by pizie11** [comment]
> > Maybe! iirc all assistants are currently only changeable by the HoP, but I don't see why any head cant do it, since they answer to "absolutley everyone"
> 
> Do you mean, allow Heads Of Staff to paint the relevant assistant trims with their ID/PDA printer and ID console?

Yes, and after testing it, this is possible

**Pull request merged**
